name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build dependency-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        id: jdk-11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build
        id: build
        run: |
          ./gradlew build
