name: Pull Requests

on:
  pull_request:

jobs:
  build:
    name: Build dependency-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        id: jdk-11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build
        id: build
        run: |
          ./gradlew build
      - name: Archive Test Report
        id: archive-reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: it-test-logs
          retention-days: 7
          path: build/reports/tests/**
